<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by Games Shop</title>
</head>
<body>

<p>Thank you, {{$buyers->name}} for buying games at Games Shop!</p>

<h4>Your games:</h4>

<ul class="list-group">
    @foreach($orders as $order)
    <li class="list-group-item">{{$order->discs->name}} - {{$order->discs->price}}</li>
    @endforeach
</ul>

<p>Total price: {{$total}}</p>

<p>Games will be delivered to {{$buyers->address}} on {{$buyers->date}} at {{$buyers->time}}.</p>

<p>Thank you!</p>

</body>
</html>
