<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by Games Shop</title>
</head>
<body>

<p>Thank you for buying games at Games Shop!</p>

<h4>Your games:</h4>

@foreach($data as $d)
   <li class="list-group-item">{{$d->discs->name}} - {{$d->discs->price}} rub</li>
@endforeach

<p>We will be happy to see you soon!</p>

</body>
</html>
